name: Deploy to Digital Ocean Content Lynx
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean Content Lynx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CANDIDATE_CONTENT_LYNX_HOST }}
          username: ${{ secrets.CANDIDATE_CONTENT_LYNX_USERNAME }}
          password: ${{ secrets.CANDIDATE_CONTENT_LYNX_PASSWORD }}
          debug: true
          script: |
            cd ${{ secrets.CANDIDATE_CONTENT_LYNX_DOCROOT }}
            git fetch origin prod
            git checkout prod
            git pull origin prod
